name: gemini_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  image_picker: ^1.2.0
  flutter_chat_ui: ^2.9.0
  uuid: ^4.5.1
  dio: ^5.9.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
